package com.example.currencyconverter

/**
 * ISO 4217 currency metadata: code -> display name and symbol.
 *
 * The set of currencies the app actually offers is driven by whatever the live
 * rates feed returns, so any code missing here still works — it simply shows
 * its raw code as the label.
 */
object Currencies {

    data class Info(val name: String, val symbol: String)

    val map: Map<String, Info> = mapOf(
        "AED" to Info("UAE Dirham", "د.إ"),
        "AFN" to Info("Afghan Afghani", "؋"),
        "ALL" to Info("Albanian Lek", "L"),
        "AMD" to Info("Armenian Dram", "֏"),
        "ANG" to Info("Netherlands Antillian Guilder", "ƒ"),
        "AOA" to Info("Angolan Kwanza", "Kz"),
        "ARS" to Info("Argentine Peso", "$"),
        "AUD" to Info("Australian Dollar", "$"),
        "AWG" to Info("Aruban Florin", "ƒ"),
        "AZN" to Info("Azerbaijani Manat", "₼"),
        "BAM" to Info("Bosnia-Herzegovina Convertible Mark", "KM"),
        "BBD" to Info("Barbadian Dollar", "$"),
        "BDT" to Info("Bangladeshi Taka", "৳"),
        "BGN" to Info("Bulgarian Lev", "лв"),
        "BHD" to Info("Bahraini Dinar", ".د.ب"),
        "BIF" to Info("Burundian Franc", "FBu"),
        "BMD" to Info("Bermudan Dollar", "$"),
        "BND" to Info("Brunei Dollar", "$"),
        "BOB" to Info("Bolivian Boliviano", "Bs."),
        "BRL" to Info("Brazilian Real", "R$"),
        "BSD" to Info("Bahamian Dollar", "$"),
        "BTN" to Info("Bhutanese Ngultrum", "Nu."),
        "BWP" to Info("Botswanan Pula", "P"),
        "BYN" to Info("Belarusian Ruble", "Br"),
        "BZD" to Info("Belize Dollar", "BZ$"),
        "CAD" to Info("Canadian Dollar", "$"),
        "CDF" to Info("Congolese Franc", "FC"),
        "CHF" to Info("Swiss Franc", "CHF"),
        "CLP" to Info("Chilean Peso", "$"),
        "CNY" to Info("Chinese Yuan", "¥"),
        "COP" to Info("Colombian Peso", "$"),
        "CRC" to Info("Costa Rican Colón", "₡"),
        "CUP" to Info("Cuban Peso", "$"),
        "CVE" to Info("Cape Verdean Escudo", "$"),
        "CZK" to Info("Czech Koruna", "Kč"),
        "DJF" to Info("Djiboutian Franc", "Fdj"),
        "DKK" to Info("Danish Krone", "kr"),
        "DOP" to Info("Dominican Peso", "RD$"),
        "DZD" to Info("Algerian Dinar", "دج"),
        "EGP" to Info("Egyptian Pound", "£"),
        "ERN" to Info("Eritrean Nakfa", "Nfk"),
        "ETB" to Info("Ethiopian Birr", "Br"),
        "EUR" to Info("Euro", "€"),
        "FJD" to Info("Fijian Dollar", "$"),
        "FKP" to Info("Falkland Islands Pound", "£"),
        "FOK" to Info("Faroese Króna", "kr"),
        "GBP" to Info("British Pound Sterling", "£"),
        "GEL" to Info("Georgian Lari", "₾"),
        "GGP" to Info("Guernsey Pound", "£"),
        "GHS" to Info("Ghanaian Cedi", "₵"),
        "GIP" to Info("Gibraltar Pound", "£"),
        "GMD" to Info("Gambian Dalasi", "D"),
        "GNF" to Info("Guinean Franc", "FG"),
        "GTQ" to Info("Guatemalan Quetzal", "Q"),
        "GYD" to Info("Guyanaese Dollar", "$"),
        "HKD" to Info("Hong Kong Dollar", "$"),
        "HNL" to Info("Honduran Lempira", "L"),
        "HRK" to Info("Croatian Kuna", "kn"),
        "HTG" to Info("Haitian Gourde", "G"),
        "HUF" to Info("Hungarian Forint", "Ft"),
        "IDR" to Info("Indonesian Rupiah", "Rp"),
        "ILS" to Info("Israeli New Shekel", "₪"),
        "IMP" to Info("Isle of Man Pound", "£"),
        "INR" to Info("Indian Rupee", "₹"),
        "IQD" to Info("Iraqi Dinar", "ع.د"),
        "IRR" to Info("Iranian Rial", "﷼"),
        "ISK" to Info("Icelandic Króna", "kr"),
        "JEP" to Info("Jersey Pound", "£"),
        "JMD" to Info("Jamaican Dollar", "J$"),
        "JOD" to Info("Jordanian Dinar", "د.ا"),
        "JPY" to Info("Japanese Yen", "¥"),
        "KES" to Info("Kenyan Shilling", "KSh"),
        "KGS" to Info("Kyrgystani Som", "с"),
        "KHR" to Info("Cambodian Riel", "៛"),
        "KID" to Info("Kiribati Dollar", "$"),
        "KMF" to Info("Comorian Franc", "CF"),
        "KRW" to Info("South Korean Won", "₩"),
        "KWD" to Info("Kuwaiti Dinar", "د.ك"),
        "KYD" to Info("Cayman Islands Dollar", "$"),
        "KZT" to Info("Kazakhstani Tenge", "₸"),
        "LAK" to Info("Laotian Kip", "₭"),
        "LBP" to Info("Lebanese Pound", "£"),
        "LKR" to Info("Sri Lankan Rupee", "₨"),
        "LRD" to Info("Liberian Dollar", "$"),
        "LSL" to Info("Lesotho Loti", "L"),
        "LYD" to Info("Libyan Dinar", "ل.د"),
        "MAD" to Info("Moroccan Dirham", "د.م."),
        "MDL" to Info("Moldovan Leu", "L"),
        "MGA" to Info("Malagasy Ariary", "Ar"),
        "MKD" to Info("Macedonian Denar", "ден"),
        "MMK" to Info("Myanmar Kyat", "K"),
        "MNT" to Info("Mongolian Tugrik", "₮"),
        "MOP" to Info("Macanese Pataca", "MOP$"),
        "MRU" to Info("Mauritanian Ouguiya", "UM"),
        "MUR" to Info("Mauritian Rupee", "₨"),
        "MVR" to Info("Maldivian Rufiyaa", "Rf"),
        "MWK" to Info("Malawian Kwacha", "MK"),
        "MXN" to Info("Mexican Peso", "$"),
        "MYR" to Info("Malaysian Ringgit", "RM"),
        "MZN" to Info("Mozambican Metical", "MT"),
        "NAD" to Info("Namibian Dollar", "$"),
        "NGN" to Info("Nigerian Naira", "₦"),
        "NIO" to Info("Nicaraguan Córdoba", "C$"),
        "NOK" to Info("Norwegian Krone", "kr"),
        "NPR" to Info("Nepalese Rupee", "₨"),
        "NZD" to Info("New Zealand Dollar", "$"),
        "OMR" to Info("Omani Rial", "ر.ع."),
        "PAB" to Info("Panamanian Balboa", "B/."),
        "PEN" to Info("Peruvian Sol", "S/."),
        "PGK" to Info("Papua New Guinean Kina", "K"),
        "PHP" to Info("Philippine Peso", "₱"),
        "PKR" to Info("Pakistani Rupee", "₨"),
        "PLN" to Info("Polish Złoty", "zł"),
        "PYG" to Info("Paraguayan Guarani", "₲"),
        "QAR" to Info("Qatari Rial", "ر.ق"),
        "RON" to Info("Romanian Leu", "lei"),
        "RSD" to Info("Serbian Dinar", "дин."),
        "RUB" to Info("Russian Ruble", "₽"),
        "RWF" to Info("Rwandan Franc", "FRw"),
        "SAR" to Info("Saudi Riyal", "ر.س"),
        "SBD" to Info("Solomon Islands Dollar", "$"),
        "SCR" to Info("Seychellois Rupee", "₨"),
        "SDG" to Info("Sudanese Pound", "ج.س."),
        "SEK" to Info("Swedish Krona", "kr"),
        "SGD" to Info("Singapore Dollar", "$"),
        "SHP" to Info("Saint Helena Pound", "£"),
        "SLE" to Info("Sierra Leonean Leone", "Le"),
        "SOS" to Info("Somali Shilling", "Sh"),
        "SRD" to Info("Surinamese Dollar", "$"),
        "SSP" to Info("South Sudanese Pound", "£"),
        "STN" to Info("São Tomé and Príncipe Dobra", "Db"),
        "SYP" to Info("Syrian Pound", "£"),
        "SZL" to Info("Swazi Lilangeni", "L"),
        "THB" to Info("Thai Baht", "฿"),
        "TJS" to Info("Tajikistani Somoni", "SM"),
        "TMT" to Info("Turkmenistani Manat", "m"),
        "TND" to Info("Tunisian Dinar", "د.ت"),
        "TOP" to Info("Tongan Paʻanga", "T$"),
        "TRY" to Info("Turkish Lira", "₺"),
        "TTD" to Info("Trinidad and Tobago Dollar", "TT$"),
        "TVD" to Info("Tuvaluan Dollar", "$"),
        "TWD" to Info("New Taiwan Dollar", "NT$"),
        "TZS" to Info("Tanzanian Shilling", "TSh"),
        "UAH" to Info("Ukrainian Hryvnia", "₴"),
        "UGX" to Info("Ugandan Shilling", "USh"),
        "USD" to Info("United States Dollar", "$"),
        "UYU" to Info("Uruguayan Peso", "\$U"),
        "UZS" to Info("Uzbekistani Som", "so'm"),
        "VES" to Info("Venezuelan Bolívar", "Bs."),
        "VND" to Info("Vietnamese Dong", "₫"),
        "VUV" to Info("Vanuatu Vatu", "VT"),
        "WST" to Info("Samoan Tala", "WS$"),
        "XAF" to Info("Central African CFA Franc", "FCFA"),
        "XCD" to Info("East Caribbean Dollar", "$"),
        "XDR" to Info("Special Drawing Rights", "SDR"),
        "XOF" to Info("West African CFA Franc", "CFA"),
        "XPF" to Info("CFP Franc", "₣"),
        "YER" to Info("Yemeni Rial", "﷼"),
        "ZAR" to Info("South African Rand", "R"),
        "ZMW" to Info("Zambian Kwacha", "ZK"),
        "ZWL" to Info("Zimbabwean Dollar", "$"),
    )

    fun name(code: String): String = map[code]?.name ?: code

    fun symbol(code: String): String = map[code]?.symbol ?: ""

    /** Dropdown label, e.g. "USD — United States Dollar". */
    fun label(code: String): String {
        val n = map[code]?.name
        return if (n != null) "$code — $n" else code
    }
}
